openapi: "3.0.0"
info:
  version: '1.0'
  title: RatingsAPI
  description: |
    Televison Ratings api for Adult Swim Saturday Night Toonami Block. 
    Known Issues:
      - Missing 2017-06-03 until 2018-11-03
servers:
  - url: https

components:
  schemas:
    # Schema for error response body
    responseError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    televisionRating:
      type: object
      required: [RATINGS_OCCURRED_ON, TIME, SHOW, TOTAL_VIEWERS, YEAR]
        
      properties:
        RATINGS_OCCURRED_ON:
          description: Saturday night of the adult swim toonami block
          format: date 
          type: string
        TIME:
          description: timeslot of the show
          type: string          
        SHOW:
          description: Name of show
          type: string

        TOTAL_VIEWERS:
          description: |
            Number of people who watched the show in thousands.
          type: integer

        YEAR:
          description: Year the television rating occurred in
          type: integer

        PERCENTAGE_OF_HOUSEHOLDS:
          description: |
            Percentage of households who were watching the show. 
            1.0 equates to one percent of households with a television
            on at that time for all viewers were watching the show.
          type: number

        TOTAL_VIEWERS_AGE_18_49:
          description: |
            Number of viewers age 18 to 49 who watched the show in thousands.
          type: integer

        PERCENTAGE_OF_HOUSEHOLDS_AGE_18_49:
          description: |
            Percentage of households where the viewer is age 18 to 49 
            with a televion on at that time watching the show. 
            1.0 equates to one percent of households with a television
            on at that time for viewers age 18 to 49 were watching the show.
          type: number

        IS_RERUN:
          description: If the show is a rerun          
          type: boolean

  responses:
    badRequest:
      description: HTTP 400 error 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
          example:
            message: 'Invalid path parameter'

    badRequestSearch:
      description: HTTP 400 error 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
          example:
            message: Query parameters startDate and endDate are required

    notFoundNight:
      description: HTTP 404 error 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
          example:
            message: 'night: 3005-11-28 not found'

    notFoundSearch:
      description: HTTP 404 error 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
          example:
            message: 'startDate must be less than or equal to endDate'

    notFoundShow:
      description: HTTP 404 error 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
          example:
            message: 'show: Corey in the House not found'

    notFoundYear:
      description: HTTP 404 error 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
          example:
            message: 'year: 3005 not found'

paths:
  /{version}/nights/{night}:
    get:
      description: |
        Returns all the ratings associated with a given night. 
      parameters:
        - name: version
          in: path
          description: Version of api to use
          required: true
          schema:
            type: string  
                
        - name: night
          in: path
          description: Saturday night ratings in YYYY-MM-DD format
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: All shows for a broadcast run of Toonami
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/televisionRating'
                example:
                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '12:00'
                    SHOW: Dragon Ball Z Kai
                    TOTAL_VIEWERS: 1293
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.62
                    TOTAL_VIEWERS_AGE_18_49: 802

                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '12:30'
                    SHOW: Jojo's Bizarre Adventure
                    TOTAL_VIEWERS: 995
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.48
                    TOTAL_VIEWERS_AGE_18_49: 613  

                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '1:00'
                    SHOW: 'Gundam: Iron-Blooded Orphans'
                    TOTAL_VIEWERS: 878
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.41
                    TOTAL_VIEWERS_AGE_18_49: 530         
  

                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '1:30'
                    SHOW: Hunter x Hunter
                    TOTAL_VIEWERS: 860
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.40
                    TOTAL_VIEWERS_AGE_18_49: 516    

                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '2:00'
                    SHOW: Naruto Shippuden
                    TOTAL_VIEWERS: 848
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.36
                    TOTAL_VIEWERS_AGE_18_49: 462    

                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '2:30'
                    SHOW: One Piece
                    TOTAL_VIEWERS: 674
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.32
                    TOTAL_VIEWERS_AGE_18_49: 409  

                  - RATINGS_OCCURRED_ON: '2016-11-05'
                    TIME: '3:00'
                    SHOW: Children Who Chase Lost Voices
                    TOTAL_VIEWERS: 492
                    YEAR: 2016
                    PERCENTAGE_OF_HOUSEHOLDS: 0.25
                    TOTAL_VIEWERS_AGE_18_49: 326    

        '400':
          $ref: '#/components/responses/badRequest'

        '404':
          $ref: '#/components/responses/notFoundNight'


  /{version}/search/:
    get:
      description: |
        Return all saturday night ratings by searching with a startDate
        and endDate. The search will be inclusive and a next key will be provided in the response
        for pagination if the search criteria covers multiple years.                      
        
        In the response example provided the original client request was 

        /v1/search?startDate=2019-12-21&endDate=2020-06-13

        The actual response returned from the api will have all shows on 2019-12-21 and 2019-12-28
        but the below response was truncated to only the first shows for brevity (AKA - developer laziness).
        The next url key will not be provided in the response if the 
        startDate and endDate do not cover overlapping years

      parameters:
        - name: version
          in: path
          description: Version of api to use
          required: true
          schema:
            type: string  
                
        - name: endDate
          in: query
          description: inclusive end date for search in YYYY-MM-DD format
          required: true
          schema:
            type: string
            format: date

        - name: startDate
          in: query
          description: inclusive start date for search in YYYY-MM-DD format
          required: true
          schema:
            type: string
            format: date

      responses:
        '200':
          description: |
            All shows that meet the startDate and endDate query parameters criteria. 
            The startDate and endDate are included in the results
          content:
            application/json:
              schema:
                type: object
                properties:
                  next: 
                    type: string
                    description: Not present if pagination is not required
                    example:
                      /search?startDate=2020-01-04&endDate=2020-06-13
                  ratings:
                    type: array
                    items:
                        $ref: '#/components/schemas/televisionRating'
                    example:
                      - RATINGS_OCCURRED_ON: '2019-12-21'
                        TIME: '11:00'
                        SHOW: One Punch Man
                        TOTAL_VIEWERS: 493
                        YEAR: 2019
                        PERCENTAGE_OF_HOUSEHOLDS_AGE_18_49: 0.22
                        IS_RERUN: true
                        TOTAL_VIEWERS_AGE_18_49: 285

                      - RATINGS_OCCURRED_ON: '2019-12-28'
                        TIME: '11:00'
                        SHOW: Dr. Stone
                        TOTAL_VIEWERS: 312
                        YEAR: 2019
                        PERCENTAGE_OF_HOUSEHOLDS_AGE_18_49: 0.12
                        IS_RERUN: true
                        TOTAL_VIEWERS_AGE_18_49: 158

        '400':
          $ref: '#/components/responses/badRequestSearch'

        '404':
          $ref: '#/components/responses/notFoundSearch'



  /{version}/shows/{show}:
    get:
      description: |
        Returns all the ratings associated with the given show. Can span years
        if the show was on during multiple years
      parameters:
        - name: version
          in: path
          description: Version of api to use
          required: true
          schema:
            type: string  
                
        - name: show
          in: path
          description: name of the show to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: show response
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/televisionRating'
                example:
                  - RATINGS_OCCURRED_ON: '2013-04-27'
                    TIME: '2:00'
                    SHOW: IGPX
                    TOTAL_VIEWERS: 848
                    YEAR: 2013
                    PERCENTAGE_OF_HOUSEHOLDS: 0.80
                    TOTAL_VIEWERS_AGE_18_49: 404


                  - RATINGS_OCCURRED_ON: '2013-05-04'
                    TIME: '2:00'
                    SHOW: IGPX
                    TOTAL_VIEWERS: 776
                    YEAR: 2013
                    PERCENTAGE_OF_HOUSEHOLDS: 0.60
                    TOTAL_VIEWERS_AGE_18_49: 392

                  - RATINGS_OCCURRED_ON: '2014-01-04'
                    TIME: '4:30'
                    SHOW: IGPX
                    TOTAL_VIEWERS: 462
                    YEAR: 2014
                    PERCENTAGE_OF_HOUSEHOLDS: 0.40                  
  
        '400':
          $ref: '#/components/responses/badRequest'

        '404':
          $ref: '#/components/responses/notFoundShow'

  /{version}/years/{year}:
    get:
      description: |
        Returns all the ratings associated with the given year.
      parameters:
        - name: version
          in: path
          description: Version of api to use
          required: true
          schema:
            type: string  
                
        - name: year
          in: path
          description: year you want to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: year response
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/televisionRating'
                example:
                  - RATINGS_OCCURRED_ON: '2013-04-27'
                    TIME: '2:00'
                    SHOW: IGPX
                    TOTAL_VIEWERS: 848
                    YEAR: 2013
                    PERCENTAGE_OF_HOUSEHOLDS: 0.80
                    TOTAL_VIEWERS_AGE_18_49: 404


                  - RATINGS_OCCURRED_ON: '2013-05-04'
                    TIME: '2:00'
                    SHOW: IGPX
                    TOTAL_VIEWERS: 776
                    YEAR: 2013
                    PERCENTAGE_OF_HOUSEHOLDS: 0.60
                    TOTAL_VIEWERS_AGE_18_49: 392

                  - RATINGS_OCCURRED_ON: '2013-11-23'
                    TIME: '3:00'
                    SHOW: Star Wars the Clone Wars
                    TOTAL_VIEWERS: 750
                    YEAR: 2013
                    PERCENTAGE_OF_HOUSEHOLDS: 0.60           
  
        '400':
          $ref: '#/components/responses/badRequest'

        '404':
          $ref: '#/components/responses/notFoundYear'